# Generated by Django 5.1.2 on 2024-10-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_store_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='email',
        ),
        migrations.AddField(
            model_name='store',
            name='opening_days',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
