# Generated by Django 5.1.2 on 2024-10-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_remove_store_email_store_opening_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
        migrations.AddField(
            model_name='store',
            name='image1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='image2',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='image3',
            field=models.URLField(null=True),
        ),
    ]
