# Generated by Django 5.1.2 on 2024-10-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0010_alter_store_id_storeproducts'),
        ('product', '0004_rename_product_category_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(related_name='stores', to='product.product'),
        ),
        migrations.DeleteModel(
            name='StoreProducts',
        ),
    ]
