# Generated by Django 5.1.2 on 2024-10-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0011_store_products_delete_storeproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='image1',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='image2',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='image3',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='location_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_days',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_hours',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
