# Generated by Django 5.1.2 on 2024-10-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0012_alter_store_address_alter_store_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
    ]
