# Generated by Django 5.1.2 on 2024-10-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category",
            new_name="name",
        ),
    ]
