# Generated by Django 5.1.2 on 2024-10-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_rename_category_category_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="product",
            new_name="products",
        ),
    ]
