# Generated by Django 5.1.2 on 2024-10-25 00:43

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "products.json")

class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_rename_product_category_products"),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
