# Generated by Django 5.1.2 on 2024-10-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('publication_date', models.DateField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
