# Generated by Django 5.1.2 on 2024-10-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_comment_remove_article_is_published_and_more'),
        ('article', '0004_alter_article_publication_date'),
    ]

    operations = [
    ]
